# -*- coding: utf-8 -*-
"""Verdicts from the Mathematics Standard 2 written-answer review, 2026-09-07.

All 145 written questions in subjects/mathematics-standard-2.json were compared
against NESA's committed sample answers and criteria rows in
data/answer-key/written/mathematics-standard-2.json. The marking guidelines
themselves were never re-read (CLAUDE.md section 10).

Where a STEM was changed, the wording was confirmed against the exam paper itself
(NESA Exams Folder/Maths Standard 2), which CLAUDE.md's exam-citation rule requires
and which the marking-guideline rule permits -- the papers are not the guidelines.
Eight stems were checked this way and all eight were wrong.

Mechanical triage (scripts/review_triage.py) ordered the reading queue and decided
nothing; every question was read regardless of rank. Two mechanical checks were run
before the ledger was committed (scripts/review_checks.cjs, which drives the REAL
scoring.js rather than a mirror of it): every question/part scores FULL marks from
its own model answer, and no question awards ZERO at its own minKeywords. Both are
clean at 145/145. A third check -- scoring every question against fluent but
content-free student answers -- is what caught 2020 Q26 and 2021 Q28, where a wrong
answer was scoring full marks.

Consumed by scripts/build_review_ledger.py, which adds the sample-answer fingerprints.

Verdicts
--------
ok                  compared, bank agrees with NESA
corrected           a defect was found and fixed in this session
divergent-accepted  the bank legitimately reads unlike NESA's text (note required)
"""

REVIEWED_AT = "2026-09-07"

# How these verdicts were actually reached. Stated plainly because the VET ledger was
# corrected by the owner on 2026-09-06 for claiming a per-question human review it
# never had, and that overstatement propagated into seven documents before anyone
# checked. This review has had NO human sign-off at all at time of writing.
REVIEW_METHOD = ("assistant-compared against NESA's committed sample answers and criteria "
                 "rows, with the eight changed stems additionally checked against the exam "
                 "papers; NO human sign-off on any question")

_ALL = ["modelAnswer", "keywords", "bandDescriptors"]

REVIEWED = {
    # -- 2020 ------------------------------------------------------------
    ('2020', '17'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('8/5×5 = ^x where x is the required number of trees 1000 × 1000 ∴ x = 8000000/25 = 320 000 spann...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '20'): {"verdict": 'corrected', "fields": _ALL, "note": "STEM DEFECT, and a whole damage class. The stem read 'a taxable income of 22 680' and 'he paid 000 per month in PAYG tax' -- the leading '$1' and '$3' had been eaten. In JavaScript, String.replace() treats $1..$9 in the REPLACEMENT string as capture-group references, so '$122 680' becomes '22 680' and '$3000' becomes '000'. The question was unanswerable as printed. Restored from the paper (2020 p16: 'a taxable income of $122 680 ... he paid $3000 per month'), which also matches NESA's own working (20 797 + 0.37(122 680 - 90 000) = $32 888.60; 3000 x 12 = $36 000; refund $3111.40). A sweep for the same signature across all five subjects found exactly one other instance, 2021 Q40."},
    ('2020', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '29'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Total dividend from company ABC = 200 × 0.06 × 5.5 = 66 Dividend for XYZ = _= 149.52 _83.52 – 6...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '34'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '35'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('128 corresponds to 2 standard deviations above the mean ∴ 5%/2 = 2.5% have an IQ score higher t...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '37'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Present value of $1000 annuity for 20 years 16.351 × 1000 = $16 351 Present value of $3000 annu...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '26'): {"verdict": 'corrected', "fields": _ALL, "note": "SCORING DEFECT: a content-free answer scored FULL marks. The critical path 'C - D - E - F - H - I' had been split into six SINGLE-LETTER keywords ('c','d','e','f','h','i'), and keywordHit() does a plain substring test, so each fires on ordinary English -- 'Activity', 'EST', 'Float' between them contain c, e, f and i. Measured in the real engine: a fluent but content-free answer scored 1/1 on part (a) and 2/2 on part (b). Parts (a) and (b) now use acceptableAnswers (the answer 46, and the critical path in the separator forms a student actually writes); part (c) keeps keywords but they are the table's own values 12, 15 and 20. Content was correct throughout and is unchanged; NESA agrees on 46 minutes, C-D-E-F-H-I, and A: EST 0 / float 12, G: EST 20 / float 15. ALSO EDITED LATER THE SAME DAY, by the Mathematics Advanced review's repo-wide label sweep: part (c)'s prompt carried a duplicated '(2 marks)' that the earlier sweep missed because a TABLE follows it, so the label is not at the end of the raw string. Presentation only."},
    ('2020', '27'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '30'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('The minimum cut passes through BD, BE, CE and CF. ∴ Maximum flow = 275 Weight of cut = _= 200 _...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '36'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2021 ------------------------------------------------------------
    ('2021', '17'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '26'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('6% ÷ 12 = 0.5% per month Future value of Option A = 35 000 (1 + 0.005)12 = $37 158.72 Interest ...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2021', '27'): {"verdict": 'corrected', "fields": _ALL, "note": "SCORING DEFECT. Part (a)'s acceptableAnswers were ['4.38', '$4.38', '5'] -- the bare '5' is part (b)'s answer, not (a)'s. scoreOne() short-circuits on acceptableAnswers using a plain includes(), so ANY answer containing the digit 5 scored 2/2 on a part whose answer is $4.38. Dropped. NESA's figures ($43.80, $4.38 and 5 years) are unchanged and agree."},
    ('2021', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2022 ------------------------------------------------------------
    ('2022', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria. EDITED LATER THE SAME DAY by the Mathematics Advanced review's repo-wide label sweep: part (b)'s prompt carried a duplicated '(2 marks)' that the earlier sweep missed because a TABLE follows it. Presentation only; no content, mark or scoring field changed, and the verdict stands."},
    ('2022', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '27'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '30'): {"verdict": 'corrected', "fields": _ALL, "note": "WRONG RESULTS in the model answer -- the worst class of defect, invisible to CI because the marks were right. It gave Option 1 as $45 093.59 and the difference as $37.29; NESA gives $45 097.17 and $40.87, and $40 000 x (1.001)^120 = $45 097.17 confirms NESA. The question's own acceptableAnswers already held '45097.17', so the bank disagreed with itself. Answer and keywords corrected to NESA's figures."},
    ('2022', '36'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '37'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '38'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2023 ------------------------------------------------------------
    ('2023', '21'): {"verdict": 'corrected', "fields": _ALL, "note": "The combined stem printed the WRONG PER-PART MARKS: (a) 1, (b) 2, (c) 1, (d) 1. The paper (2023 pp16-17) and the committed key both say (a) 1, (b) 1, (c) 1, (d) 2. The total is 5 either way, so check_written_key.cjs could not see it, but the student is told the wrong value for two parts. Corrected. Content and NESA's answers ($140, 400 kWh, Provider A by $40) are unchanged. ALSO EDITED LATER THE SAME DAY, by the Mathematics Advanced review's repo-wide label sweep: part (a)'s prompt carried a duplicated '(1 mark)' that the earlier sweep missed because a TABLE follows it. Presentation only."},
    ('2023', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2024 ------------------------------------------------------------
    ('2024', '17'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('650/1000 # 6 # $0.3013 = $1.18'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '20'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('$200 # 10.0266 = $2005.32 r = 4/2 % = 2% n = 3 # 2 = 6 Investment per 6 months = 4500/6.4343 = ...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2024', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2024', '23'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Normal time earnings = _= _1710 38 # 45 Overtime paid = 2790 - 1710 = 1080 Overtime hours = $10...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '24'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('10^1.2 # _5.5 3h _# -7.5 _60 # 2.5 BAC = = 0.0522... = 0.052 (to 3 decimal places) Time = 0.052...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '25'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Alex’s interest after 5 years = 1800 # 7.5% # 5 = $675 4 × 5 Jun’s investment at 5 years = 1800...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '27'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Repayments for 5 years at 280 = 280 # 12 # 5 = 16 800 Repayments for 7 years at 250 = 21 000 To...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    # -- 2025 ------------------------------------------------------------
    ('2025', '16'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Cost of ten-litre cans: _= $205 _$1640 × 8 Cost of four-litre cans: _= $90 _$1800 × 20 Savings ...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '18'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Amount _= = _$61 $5000 _440 × 12.288'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '27'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Interest days = 68 − 45 = 23 23 Amount = $392 1 + 13.74/365 % = $395.41 Interest charged = _= $...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '29'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('6/15 Blue 7/16 ^Blue 9/15 Yellow 7/15 Blue 9/16 Yellow 8/15 Yellow P (BB) + P (YY) = 7/16 × 6/1...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '33'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it is empty, so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '34'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('n = 7 × 12 r = 6/12 = 84 periods 84 21 000 1 + 6/12 % = 31 927.76 ` Monthly deposit = _= $31 _$...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    # -- 2020 ------------------------------------------------------------
    ('2020', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2020', '25'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Height of triangle = 11 – 8 = 3 Five square faces = _= 82 _320 × 5 Two triangular faces = 3×8/2...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '31'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('100° – 35° = 65° diagram AB2 = 72 + 92 − 2 × 7 × 9 cos65° = 76.75… AB = 8.76 km sinA/9 = sin65°...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '32'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('triangle AB = 80 ÷ 10 = 8 cm ∠AOB = 360° ÷ 10 = 36° ∠OAB = 180°−36°/2 = 72° r/sin72° = 8/sin36°...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2020', '33'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2021 ------------------------------------------------------------
    ('2021', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '23'): {"verdict": 'corrected', "fields": _ALL, "note": "TWO defects. (1) The model answer's minimum-spanning-tree edge list was FABRICATED: it named 'Kingsville-Underwood=20' where the paper's K-U edge is 65, its listed edges summed to 95 against the stated 160, and it ended in a literal '+...' shown to the student. The tree was recomputed from the committed crop (Minertown-Walltown 10, Walltown-Parktown 15, Minertown-Underwood 20, Walltown-Fernville 20, Kingsville-Minertown 25, Queentown-Kingsville 30, Parktown-Citadel 40 = 160), which reproduces NESA's 160 exactly. (2) Part (b)'s prompt asked for 'Queentown to Fernville along the minimum spanning tree'; the paper (2021 p19) asks 'How long does it take to travel from Queentown to Underwood using the fastest route?' -- a different destination, and not restricted to the tree. Restored, and the answer now shows the 45 + 20 = 65 route NESA gives."},
    ('2021', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '28'): {"verdict": 'corrected', "fields": _ALL, "note": "SCORING DEFECT. Part (b) is 1 mark with the single keyword 'increase'. keywordHit()'s kw.startsWith(word) branch means the ordinary word 'in' credits it, so a content-free answer scored 1/1 -- measured in the real engine. Converted to acceptableAnswers ('increase', 'increases', 'greater', 'steeper', 'larger'), which uses a plain includes() that 'in' does not satisfy. NESA's answer ('It would increase.') is unchanged."},
    ('2021', '32'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '33'): {"verdict": 'corrected', "fields": _ALL, "note": "STEM DEFECT: the stem contradicted both NESA and its own model answer. It gave the regression line as y = 29.2 - 0.00404x and said 'The gradient of the regression line is -0.00404'; the paper (2021 p28) prints y = 29.2 - 0.011x and '-0.011', which is what NESA's sample answer and the bank's own model answer both use (29.2 - 0.011 x 540 = 23.3 degrees C). A student following the printed stem gets 27.0 and is marked wrong. Corrected in the stem, the shared stem and the part (a) prompt."},
    ('2021', '34'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '35'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '36'): {"verdict": 'corrected', "fields": _ALL, "note": "SCORING DEFECT: a REGEX was stored as a keyword. Part (b)'s keywords included 'a.*c.*d.*e.*g.*j.*k'. keywordHit() never evaluates regexes -- it credited the string via the bare letter 'a' (kw.startsWith(word)), so it fired on almost any answer while never matching as intended. Replaced with acceptableAnswers holding the path A-C-D-E-G-J-K in the usual separator forms. NESA's answers (40 minutes, A-C-D-E-G-J-K, float 1 minute) are unchanged and agree."},
    ('2021', '37'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '38'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2021', '39'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('466 = 1/2 × 28 × 35 × sinC ˆOB ∴ sinC OB ˆ = 0.95102… ∴ C ˆOB = 72° (nearest degree) D ˆOC = _=...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2021', '40'): {"verdict": 'corrected', "fields": _ALL, "note": "The same $1..$9 loss as 2020 Q20, this time in the MODEL ANSWER and the band descriptors. It read 'Annuity: 000 per year', 'FV = 1000 x 8.2132 = 213.20' and '= 419.81', against NESA's '1000 x 8.2132 = $8213.20' and '= $8419.81'. The student was shown arithmetic that does not work. Restored; the keywords ('8213.20', '8419.81') were already right, which is how the loss was spotted -- and note they had been scoring anyway only because the bare digit '8' in 'for 8 years' credits them through keywordHit's prefix rule."},
    ('2021', '41'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2022 ------------------------------------------------------------
    ('2022', '17'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '26'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Using ABC, tan 41° = AB/35 so AB = 35 tan 41° Using ABD, sinθ = AB/93 ie sinθ = 35tan41°/93 θ =...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2022', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria. EDITED LATER THE SAME DAY by the Mathematics Advanced review's sibling-part keyword sweep: part (b) carried '5', which is part (c)'s figure and matched (b)'s own model answer only inside 35, as a suffix fragment of a longer number. Measured as a no-op on every probe in the real engine before dropping it. Content unchanged and the verdict stands."},
    ('2022', '32'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '33'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '34'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2022', '35'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2023 ------------------------------------------------------------
    ('2023', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '17'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '26'): {"verdict": 'corrected', "fields": _ALL, "note": "AUTHORING SCRATCH-WORK shown to the student. Part (a)'s model answer read 'Area with path = (3 + 0.5 + 0.5) x (8 + 0.5) = 4 x 8.5 = 34 m2... Actually: ... Inner garden area = 3 x 8 = 24 m2... From MG: Area of path = (3 x 8) - (7 x 2.5) = 6.5 m2' -- two abandoned attempts and the internal phrase 'From MG:' (from the marking guidelines). Replaced with NESA's own method. The result 6.5 m2 was already right and is unchanged, as is part (b) (300 kg, 20 bags)."},
    ('2023', '27'): {"verdict": 'corrected', "fields": _ALL, "note": "AUTHORING SCRATCH-WORK shown to the student, the worst instance in the subject: part (b)'s model answer contained literal thinking-aloud -- '... cos theta = 7.5/40... no. Using right angle at P: ... XC = sqrt(XP2 + CP2) should be 40... wait Actually: ...'. Replaced with NESA's method (cos(angle CXP) = 7.5/40, 79 degrees 12', bearing 180 + 79 = 259). The final answers 7.5 km and 259 were already right and are unchanged."},
    ('2023', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '32'): {"verdict": 'corrected', "fields": _ALL, "note": "The combined stem printed (a) 3 marks and (b) 1 mark; the paper (2023 p28) and the committed key both say 2 and 2. Same class as 2023 Q21 -- totals 4 either way, so CI could not see it. Corrected. NESA's answers ($3.51 and 0.77%) are unchanged."},
    ('2023', '33'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '34'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '35'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '36'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '37'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2023', '38'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    # -- 2024 ------------------------------------------------------------
    ('2024', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2024', '18'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('A 4 ^B ^C D 2 1 2 F E 4 3 G 1 _H 4 J 3 I Weight = 24 Yes, use BC instead of FC as the weight of...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '19'): {"verdict": 'corrected', "fields": _ALL, "note": "STEM DEFECT: part (b) was UNANSWERABLE as printed. The stem said only 'Another student ... scored 5 for the assignment' and then asked whether that student did better or worse than predicted -- the student's actual test mark was missing. The paper (2024 p13) reads 'scored 5 for the assignment and 12 on the test', and NESA's sample answer ('Worse as the predicted test mark was 13 instead of 12') depends on it. Restored. The model answer already used 12 and is unchanged."},
    ('2024', '26'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('A = -0.5w2 + 20w Maximum area when width = 20 A = -0.5^20h2 + 20^20h = 200 cm2 A = h # w 200 = ...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2024', '29'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Value after 4 years: Using straight-line method = 50 000 - 1500 # 4 = 44 000 Value after the ne...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2024', '31'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('2/3 P(no heads) = 1/3 # 1/3 = 1/9 ` P(at least 1 head) = 1 - 1/9 = 8/9'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '32'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('A = p r 2 circle = p # 302 = 2827.433... A3 = 1/2 ab sin C = 1/2 # 30 # 30 sin 72° = 427.975......'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '33'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Speed = Distance/Time 40 km/h = 0.15km/T T = 0.15/40 T = 0.00375 hours T = 0.00375 # 3600 secon...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '34'): {"verdict": 'corrected', "fields": _ALL, "note": "TWO defects. (1) The stem asked for the answer 'in square centimetres, correct to the nearest whole number'; the paper (2024 p28) asks for 'square metres correct to 1 decimal place', which is what NESA's criteria ('Provides correct solution in square metres') and the bank's own model answer (0.5 m2) both use. (2) The model answer carried abandoned working with a wrong cylinder length ('2pi x 11.5 x 69 = ... = 4985.7 - 1661.9 = ...') and the internal phrase 'Actual MG calculation:'. Both corrected; the result 4985.7 cm2 = 0.5 m2 is unchanged and matches NESA."},
    ('2024', '35'): {"verdict": 'corrected', "fields": _ALL, "note": "THREE stem errors in one question, every one confirmed on paper p29, and in every case the model answer was already working NESA's version -- so stem and answer contradicted each other throughout. (1) 'standard deviation 12' should be 15 (NESA's own working is z = (70-58)/15 = 0.8). (2) Part (a) asked for 'the percentage of scores that are less than 46'; the paper asks for the percentage 'between 58 and 70' -- and the bank's answer computes exactly that (28.81%). It is also the only reading under which part (b) is true, since 2 x 28.81% = 57.62% is the percentage between 46 and 70. (3) Part (c) asked for the 'top 5%'; the paper asks for the 'top 10%', which is what z = 1.3 (P = 0.9032) and the answer's 77 or 78 give. All three corrected in the stem, the shared stem and the part prompts."},
    ('2024', '36'): {"verdict": 'corrected', "fields": _ALL, "note": "Part (b)'s model answer carried an 'Actually:' scratch marker mid-working and a bogus justification ('CD = BE - BX (vertical drop from B to C along slope)'). Replaced with NESA's own three lines. The results 25.4 m and 19.7 m were already right and are unchanged."},
    ('2024', '37'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2024', '38'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('Volume of cylinder: volume of top = 5: 1 Volume of cylinder = p # 152 # 6 = 4241.150... = 5 par...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '39'): {"verdict": 'corrected', "fields": _ALL, "note": "Part (c)'s model answer was muddled and self-cancelling: 'F starts at EST = LST of C + duration of C (actually at the EST of the next node)'. Rewritten around NESA's own working (12 - 3 = 9, 9 - 1 = 8 hours). The answers BEGI, 7 hours and 8 hours were already right and are unchanged."},
    ('2024', '40'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('In UODA: 382 + 422 - 67.52 cos EAOD = 2 # 38 # 42 = -0.42238... EAOD = 114.985.... 115° Bearing...'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2024', '41'): {"verdict": 'corrected', "fields": _ALL, "note": "AUTHORING SCRATCH-WORK shown to the student, including an instruction to itself: 'PV1 = $2000 x 151.036 = $302 072 Wait -- let me re-read the MG. MG says: ...'. The abandoned $302 072 line and the note were removed; the remaining working ($1200 x 225.430 = $270 516 plus $800 x 151.036 = $120 828.80, total $391 344.80) is NESA's and was already right."},
    # -- 2025 ------------------------------------------------------------
    ('2025', '17'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '19'): {"verdict": 'corrected', "fields": _ALL, "note": "The worst finding in the subject: the model answer was wrong on all three parts and contradicted itself. (a) It gave 'E: B' and 'F: A, C'; NESA's table is E: C, D and F: E. (b) It gave the critical path as B-F-H = 16 days; NESA gives BDEFH = 4 + 5 + 5 + 7 + 5 = 26 days, which the committed crop confirms (A 3, B 4, C 3, D 5, E 5, F 7, G 3, H 5: A->C = 6 against B->D = 9, then E, then F->H = 12 against G = 3). (c) It opened 'No -- increasing A by 2 days does not affect the critical path' and then closed 'Corrected: ... This DOES affect the critical path', contradicting both itself and NESA ('No, as the float time for activity A is 3'). Rewritten from NESA; keywords ('16' and a regex-shaped 'b.*f.*h') and bandDescriptors rebuilt around the correct path and duration."},
    ('2025', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '26'): {"verdict": 'corrected', "fields": _ALL, "note": "TWO parts asked questions the paper never asks, while their model answers worked NESA's actual questions -- so the student was shown a prompt and an answer that did not match. Paper pp22-23: (b) is 'What is the approximate area of the curved surface?' (the bank asked for a percentage, and the answer gives the area, 582.64 cm2); (c) is 'The measurements shown on the diagram are given to the nearest millimetre. What is the percentage error of the measurement of 10.2 cm? Give your answer correct to 3 significant figures.' (the bank asked for a mass of plastic, and the answer gives the percentage error, 0.490%). NESA's criteria confirm both ('Finds at least 2 correct areas as part of a surface area calculation'; 'Provides correct absolute error'). Both prompts restored; part (b)'s answer also had a 'Using MG:' leak and a '480 cm...' typo removed."},
    ('2025', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '32'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('4'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '35'): {"verdict": 'corrected', "fields": _ALL, "note": "The model answer opened with a self-cancelling parenthetical: 'the angle TAP (alternate angle) = 36 degrees (since TA is horizontal from T's perspective, but actually angle TAP = 36 degrees from the horizontal at A)'. Rewritten as one clear sentence. The working and the result 35.29 m are unchanged; NESA's sample for this question is a diagram dump, so the result was checked by recomputation (sin(angle) = 75 sin 36 / 51, obtuse angle 120 degrees, angle TPA 24 degrees, TA = 51 sin 24 / sin 36 = 35.29)."},
    ('2025', '36'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '37'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer is unusable as prose here -- it extracts as mangled equation layout ('60° 3 9 c'), so the bank's worked solution necessarily reads nothing like it. Compared NUMERICALLY instead and every figure agrees, and the band descriptors were checked against the criteria rows, which extract cleanly."},
    ('2025', '39'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '38'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria."},
    ('2025', '40'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows: the model answer's method and final result agree, every keyword is creditable from the model answer in the real engine, and the band descriptors match NESA's criteria. EDITED LATER THE SAME DAY by the Mathematics Advanced review's sibling-part keyword sweep: part (b) carried '600', which is part (a)'s male-sheep count and matched (b)'s own model answer only inside 12 600. Measured as a no-op on every probe in the real engine before dropping it. Content unchanged and the verdict stands."},
}
