# -*- coding: utf-8 -*-
"""Verdicts from the Mathematics Advanced written-answer review, 2026-09-07.

All 126 written questions in subjects/mathematics-advanced.json were read against
NESA's committed sample answers and criteria rows in
data/answer-key/written/mathematics-advanced.json. The marking guidelines themselves
were never re-read (CLAUDE.md section 10).

CONTENT WAS CLEAN. Unlike VET (6 defects in 34) and Multimedia (9 in 35), not one
result, method or figure in this subject disagrees with NESA. That is consistent with
how it was ported: uniquely among the five subjects, Mathematics Advanced was built
from the papers with the official key already committed and reconciling to 100 marks
per paper at every stage. The 31 corrections below are all scoring, teaching, rendering or
presentation defects, every one invisible to CI because the marks were right. Two of
them were found only by RENDERING the questions rather than reading the data.

On the ok / divergent-accepted split. NESA's maths sample answers extract as equation
LAYOUT, not prose, so the bank's worked solutions necessarily read nothing like them --
the comparison made here was mathematical, not textual: method, intermediate values and
final result. That comparison was possible for 120 questions and they are marked `ok`.
It was NOT possible for 6, all in 2025, where the key's sampleAnswer field is simply
empty; those are `divergent-accepted` and were checked against the question and the
criteria rows instead. (Four further blanks -- 2020 Q11(a), 2021 Q28(b), 2023 Q19(a),
2024 Q17(a) -- are for parts the bank already declares in omittedParts, so nothing was
lost there.)

Mechanical triage (scripts/review_triage.py) ordered the reading queue and decided
nothing; every question was read regardless of rank, and triage reported overlap 0.00
on almost all of them, which is the expected signature of equation-layout extraction
rather than a signal about the bank. Two standing checks ran clean at 126/126 before
the ledger was committed (scripts/review_checks.cjs, which drives the REAL scoring.js
rather than a mirror of it): every question and part scores FULL marks from its own
model answer, and none awards ZERO at its own minKeywords. A third -- scoring every
question against a fluent but content-free answer -- is also clean.

Two further checks were written for this subject. One found the four keyword leaks: a
NUMERIC keyword whose only match in its OWN model answer is preceded by a digit, making
it a suffix fragment of a longer number ("83" inside 783.7168); run repo-wide it also
found two in Standard 2, fixed in the same pass. The other -- and this one could only be
made by rendering, not by reading -- asks whether every image a question REFERENCES
actually reaches the DOM. It found 14 questions whose stimulus had been invisible to
students since 2026-09-05.

DELIBERATELY NOT CHANGED, and the reason this review probes rather than reasons:
2020 Q11(b) carries part (c)'s answer '45' by the same signature. Dropping it measured
2/2 -> 1/2 on a fully correct working, because that working writes "450" and the
keyword was carrying the match. It stays, and the question is marked corrected only for
its duplicated mark label.

Consumed by scripts/build_review_ledger.py, which adds the sample-answer fingerprints.

Verdicts
--------
ok                  compared, bank agrees with NESA
corrected           a defect was found and fixed in this session
divergent-accepted  the bank legitimately reads unlike NESA's text (note required)
"""

REVIEWED_AT = "2026-09-07"

# How these verdicts were actually reached. Stated plainly because the VET ledger was
# corrected by the owner on 2026-09-06 for claiming a per-question human review it never
# had, and that overstatement propagated into seven documents before anyone checked.
# This review has had NO human sign-off at all at time of writing.
REVIEW_METHOD = ("assistant-compared against NESA's committed sample answers and criteria "
                 "rows, question by question, with the mathematics checked rather than the "
                 "wording; NO human sign-off on any question")

_ALL = ["modelAnswer", "keywords", "bandDescriptors"]

REVIEWED = {
    # -- 2020 ------------------------------------------------------
    ('2020', '11'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (1 mark) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (a) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2020', '12'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '13'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '14'): {"verdict": 'corrected', "fields": _ALL, "note": "SCORING DEFECT (sibling-part keyword leak). Part (c) carried the keyword '5', which is part (b)'s figure -- (c)'s own model answer contains it only INSIDE 1560, as a suffix fragment. Measured in the real engine: a correct answer of '10/39' scored 1/2 before and 2/2 after dropping it. Content unchanged and agrees with NESA (10/39)."},
    ('2020', '15'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2020', '17'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '26'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '27'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2020', '29'): {"verdict": 'corrected', "fields": _ALL, "note": "TOOLING HAZARD (corrected 2026-09-08 -- this was first written up as a rendering defect and that was WRONG). The stimulus image's alt attribute read alt=\"Graph of y = c ln x for c > 0, ...\". Browsers handle that correctly: asked directly, the pre-fix string parses to exactly one <img> with its full alt and style intact and nothing leaked as text, because inside a double-quoted attribute value '<' and '>' are ordinary characters. What the bare '>' does break is this repo's own regex parsing of markup -- the <img[^>]*> in scripts/archive/mathsadv_add_parts.py, whose docstring records it losing this very question's image, and the live /<img[^>]+src=\"([^\"]+)\"/g in validate_subjects.cjs. Escaped to &gt; so the data is safe for that tooling. One instance repo-wide. No content changed; the solution agrees with NESA (c = e). ALSO: RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2020', '30'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2020', '31'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    # -- 2021 ------------------------------------------------------
    ('2021', '11'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '12'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '13'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '14'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '15'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '17'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (1 mark) sitting directly under the accordion header that already reads the same marks -- here it was also in the wrong place, stranded mid-sentence after the description of the graph rather than after a question. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2021', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '26'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '27'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (1 mark) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (a) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2021', '28'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (1 mark) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (b) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2021', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '32'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '33'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2021', '34'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    # -- 2022 ------------------------------------------------------
    ('2022', '11'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '12'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: this is a SINGLE-part question, so `q` is exactly what the student reads, and it ended in a literal (2 marks) sitting under the badge that already says the same thing, immediately before the note explaining the omitted part. Removed. Questions carrying SEVERAL such labels were left alone -- there each one is the only place that sub-part's value appears."},
    ('2022', '13'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '14'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '15'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '17'): {"verdict": 'corrected', "fields": _ALL, "note": "Sibling-part keyword leak: part (a) carried '23', which is part (b)'s answer and matched (a)'s model answer only inside 234. Measured as a no-op on every probe before dropping it. Content agrees with NESA (234 cards, 23 rows). ALSO: RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2022', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '26'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '27'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (2 marks) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (c) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2022', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2022', '31'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2022', '32'): {"verdict": 'corrected', "fields": _ALL, "note": "Sibling-part keyword leak: part (a) carried '83', part (b)'s answer, matched in (a) only inside the intermediate 783.7168. Measured as a no-op before dropping. Content agrees with NESA ($1381.16, 83 full payments, $931.54)."},
    # -- 2023 ------------------------------------------------------
    ('2023', '11'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '12'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '13'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '14'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '15'): {"verdict": 'corrected', "fields": _ALL, "note": "Sibling-part keyword leak: part (a) carried '40', part (b)'s period count, matched in (a) only inside 34 140. Measured as a no-op before dropping. Content agrees with NESA ($34 140 and $463 177.38)."},
    ('2023', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '17'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '18'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (1 mark) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (a) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2023', '19'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: this is a SINGLE-part question, so `q` is exactly what the student reads, and it ended in a literal (2 marks) sitting under the badge that already says the same thing, immediately before the note explaining the omitted part. Removed. Questions carrying SEVERAL such labels were left alone -- there each one is the only place that sub-part's value appears."},
    ('2023', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '25'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '26'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2023', '27'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2023', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2023', '30'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: this is a SINGLE-part question, so `q` is exactly what the student reads, and it ended in a literal (3 marks) sitting under the badge that already says the same thing, immediately before the note explaining the omitted part. Removed. Questions carrying SEVERAL such labels were left alone -- there each one is the only place that sub-part's value appears."},
    ('2023', '31'): {"verdict": 'corrected', "fields": _ALL, "note": "TEACHING DEFECT. Part (a) justified non-independence using P(S) = 4/5, which is part (b)'s result -- a student answering (a) first cannot use it. NESA argues from the values the question gives (P(F|S) = 1/8 against P(F) = 3/10). The model answer now leads with NESA's argument and keeps the P(S|F) form as a parenthetical. The conclusion was correct and is unchanged."},
    ('2023', '32'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    # -- 2024 ------------------------------------------------------
    ('2024', '11'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '12'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '13'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '14'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2024', '15'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '16'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '17'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (2 marks) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (a) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2024', '18'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '20'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2024', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '22'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2024', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '25'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (2 marks) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (b) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2024', '26'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '27'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '29'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '30'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2024', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    # -- 2025 ------------------------------------------------------
    ('2025', '11'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2025', '12'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer for the whole question (it extracts as the single character '2') is ABSENT from the key (the 2025 marking guidelines extract with several answer blocks empty), so there is no official text to compare the bank's wording against. Compared MATHEMATICALLY instead -- the method and every figure were checked against the question itself and against NESA's criteria rows, which do extract cleanly and which the band descriptors are taken from verbatim."},
    ('2025', '13'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '14'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer for part (c) is ABSENT from the key (the 2025 marking guidelines extract with several answer blocks empty), so there is no official text to compare the bank's wording against. Compared MATHEMATICALLY instead -- the method and every figure were checked against the question itself and against NESA's criteria rows, which do extract cleanly and which the band descriptors are taken from verbatim."},
    ('2025', '15'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: the part prompt ended in a literal (2 marks) sitting directly under the accordion header that already reads the same marks, immediately before the note explaining that part (b) is omitted. Removed; the separator and the text around it are untouched. No content, mark or scoring field changed."},
    ('2025', '16'): {"verdict": 'corrected', "fields": _ALL, "note": "PRESENTATION DEFECT: this is a SINGLE-part question, so `q` is exactly what the student reads, and it ended in a literal (4 marks) sitting under the badge that already says the same thing, immediately before the note explaining the omitted part. Removed. Questions carrying SEVERAL such labels were left alone -- there each one is the only place that sub-part's value appears."},
    ('2025', '17'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer for all three parts is ABSENT from the key (the 2025 marking guidelines extract with several answer blocks empty), so there is no official text to compare the bank's wording against. Compared MATHEMATICALLY instead -- the method and every figure were checked against the question itself and against NESA's criteria rows, which do extract cleanly and which the band descriptors are taken from verbatim."},
    ('2025', '18'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer for the whole question is ABSENT from the key (the 2025 marking guidelines extract with several answer blocks empty), so there is no official text to compare the bank's wording against. Compared MATHEMATICALLY instead -- the method and every figure were checked against the question itself and against NESA's criteria rows, which do extract cleanly and which the band descriptors are taken from verbatim."},
    ('2025', '19'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '20'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '21'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '22'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '23'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '24'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '25'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer for part (c) is ABSENT from the key (the 2025 marking guidelines extract with several answer blocks empty), so there is no official text to compare the bank's wording against. Compared MATHEMATICALLY instead -- the method and every figure were checked against the question itself and against NESA's criteria rows, which do extract cleanly and which the band descriptors are taken from verbatim."},
    ('2025', '26'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '27'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '28'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
    ('2025', '29'): {"verdict": 'corrected', "fields": _ALL, "note": "RENDERING DEFECT, found by rendering the question rather than by reading it. The stimulus image was in `q`, which a multi-part question NEVER renders -- the accordion draws `stem` plus each part's own prompt -- so the question said 'the diagram shows...' above no diagram. Introduced on 2026-09-05, when the per-part build split `stem` out of `q` and copied the intro TEXT but left the <img> behind. Proved rather than inferred: rendering 2020 Q29 with `parts` deleted shows 1 image, with `parts` present it shows 0. The tag was moved into `stem`, where the .parts-stem img cap (min(100%,600px), max-height 30vh) bounds it -- measured at 250x154 inside a 278px stem. 14 questions in this subject; none in Standard 2, Multimedia or HMS, and VET's two candidates were checked and are fine (their image sits in a part's `intro`, which does render)."},
    ('2025', '30'): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's committed sample answer for the whole question is ABSENT from the key (the 2025 marking guidelines extract with several answer blocks empty), so there is no official text to compare the bank's wording against. Compared MATHEMATICALLY instead -- the method and every figure were checked against the question itself and against NESA's criteria rows, which do extract cleanly and which the band descriptors are taken from verbatim."},
    ('2025', '31'): {"verdict": 'ok', "fields": _ALL, "note": "Compared against NESA's committed sample answer and criteria rows. The bank's method, every intermediate value and the final result agree; every keyword is creditable from the model answer in the real engine; and the band descriptors are NESA's own criteria rows, generated verbatim rather than authored."},
}
