# -*- coding: utf-8 -*-
"""Verdicts from the Industrial Technology - Multimedia written-answer review, 2026-09-06.

All 35 written questions in subjects/multimedia.json were compared against NESA's committed
sample answers and criteria rows in data/answer-key/written/multimedia.json. The marking
guidelines themselves were never re-read (CLAUDE.md section 10).

Mechanical triage (scripts/review_triage.py) ordered the reading queue and decided nothing.
It was also demonstrably WEAKER than the engine's own matcher here: triage reported ~20
keywords "absent from modelAnswer", but a faithful mirror of index.html's keywordHit() --
which credits a 4-character shared stem, so "calls to action" credits the keyword
"call to action" -- found only FIVE the engine genuinely cannot credit. Every question was
read regardless of rank, as docs/porting-playbook.md section 6 requires.

Consumed by scripts/build_review_ledger.py, which adds the sample-answer fingerprints.

Verdicts
--------
ok                  compared, bank agrees with NESA
corrected           a defect was found and fixed in this session
divergent-accepted  the bank legitimately reads unlike NESA's text (note required)
"""

REVIEWED_AT = "2026-09-06"

# How these verdicts were actually reached. Stated plainly because the VET ledger was
# corrected by the owner on 2026-09-06 for claiming a per-question human review it never
# had, and that overstatement propagated into seven documents before anyone checked.
# This review has had NO human sign-off at all at time of writing.
#
# It is also weaker than VET's in one specific way: the six Section III questions (Q16,
# every year) were AUTHORED by the same assistant session that reviewed them, earlier the
# same day. Self-review is weaker evidence than review of someone else's work, and those
# six entries say so in their notes.
REVIEW_METHOD = ("assistant-compared against NESA's committed sample answers and criteria "
                 "rows; NO human sign-off on any question. The six Section III questions "
                 "were authored by the same session that reviewed them")

_ALL = ["modelAnswer", "keywords", "bandDescriptors"]

# Section III (Q16) was ported earlier in this same session; see docs/HISTORY.md 2026-09-06.
_SEC3 = ("Section III, ported earlier THIS session and reviewed by the same session -- "
         "self-review, weaker evidence than an independent read. Model answers authored from "
         "NESA's committed sample answer (with the Mapping Grid that parse_paper() swallows "
         "into every (b) sample stripped out); per-part marks taken from the key and asserted "
         "against it; bandDescriptors generated VERBATIM from the criteria rows by the "
         "standing collapse rule, not authored. ")

REVIEWED = {
    # ── 2020 ────────────────────────────────────────────────────────────────
    ('2020', 11): {"verdict": 'corrected', "fields": _ALL, "note": "Answer and acceptableAnswers match NESA exactly ('Real Time Streaming Protocol'). Corrected only in that it had NO bandDescriptors, so AI marking fell back to the engine's generic 0/50/100% rubric. NESA prints ONE criteria row ('Correctly identifies RTSP'), the degenerate N=1 case: full is that row verbatim, partial and minimal state its non-attainment in the established house style -- authored text, not NESA's, and flagged here as such. Deliberately keeps acceptableAnswers rather than keywords: scoreOne() short-circuits on acceptableAnswers, which is the right mechanism for a one-fact recall question, and keywords beside it would be inert dead data (the VET 2023 16(a)(i) finding)."},
    ('2020', 12): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (optical systems track markers on the actor, movements in 3D, computers assemble the data to approximate the character's movements). The bank adds infrared cameras and the skeleton model, which is how optical mocap actually works -- an extension, not a divergence."},
    ('2020', 13): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's sample answer is a costing TABLE that extracts as run-together layout ('Item Cost per item Number required Cost Paper (ream) $25.00 30 750.00 ...'), so the bank's worked prose necessarily reads unlike it. Compared numerically instead: paper 30 reams x $25 = $750.00, black toner 7.5 rounded up to 8 x $45 = $360.00, colour toner 23.07 rounded up to 24 x $65 = $1560.00, total $2670.00. Every figure agrees, including both round-ups. NOTE a matcher looseness, not fixable per question: the keywords are numeric, and keywordHit()'s kw.startsWith(word) branch means the bare digit '2' credits the keyword '2670' and '1' credits '1560' -- so those two fire on almost any answer containing digits. Same class as the 'pi'/'pipe' looseness noted on VET 2024 19(b). Left as authored; the fix is an engine change, not a content change."},
    ('2020', 14): {"verdict": 'corrected', "fields": _ALL, "note": "Content matched NESA (convert to a smaller format, trim unwanted parts, change bit rate, resolution and frame rate). Corrected because TWO of its own keywords -- 'compress' and 'format' -- appeared nowhere in its model answer, so the engine could never credit them; a student writing NESA's own vocabulary was marked down for it. The model answer's last sentence now reads 'converting to a more efficient codec or file format (such as H.265/HEVC instead of H.264, or WMV) applies stronger compression', taking the words from NESA's own sample ('convert to a smaller sized format such as WMV', 'FLV program will also compress MP4'). Nothing else changed."},
    ('2020', 15): {"verdict": 'ok', "fields": _ALL, "note": "Covers NESA's list point for point (links to services, logo, headline with name/purpose/address/contact, site map and return links, photos or graphics, search function, content blocks, social proof/testimonials, special offers/subscriptions) and adds calls to action. Triage flagged 'call to action' as absent from the model answer; it is not -- the answer says 'Calls to action', which keywordHit() credits on the 4-character shared stem."},
    ('2020', 16): {"verdict": 'ok', "fields": _ALL, "note": _SEC3 + "(a) location factors and (b) strategies to minimise continuing environmental impact; NESA's grid files both under 'Environmental and sociological considerations'. (b)'s answer is written with points for and against, which is what NESA's top band explicitly asks for."},

    # ── 2021 ────────────────────────────────────────────────────────────────
    ('2021', 11): {"verdict": 'corrected', "fields": _ALL, "note": "TWO corrections. (1) acceptableAnswers listed only Adobe Illustrator, Corel Draw, Inkscape, Affinity Designer and the generic 'vector', but NESA also names Adobe Fireworks, PaintShop Pro, Lunacy, Draw Pad, Vecteezy Editor, Snappa, Artboard, Vector Magic, Vectornator Pro and Designimo -- a student answering with NESA's own accepted software was marked wrong. Same defect class as VET 2023 16(a)(i)'s missing 'sliding saw'. The names not already caught by the 'vector' substring were added. (2) Had no bandDescriptors; added from NESA's single criteria row (degenerate N=1, partial/minimal authored non-attainment, as 2020 Q11)."},
    ('2021', 13): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's sample extracts as mangled equation layout ('66 355 200 / (8 x 1024 x 1024) = _= 66 _7.91MB 355 200 / 8388608'), so the bank's step-by-step prose necessarily reads unlike it. Compared numerically: 1920 x 1080 = 2 073 600 pixels; x 32 bits = 66 355 200 bits; / 8 = 8 294 400 bytes; / 1 048 576 = 7.91 MB. Every figure agrees, including NESA's own 8388608 divisor route. Same numeric-keyword looseness as 2020 Q13 -- the single-character keyword '8' fires on any answer containing an 8."},
    ('2021', 14): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA's structure (compression reduces file size for sharing; lossy = smaller files, quality lost, MP4 the example; lossless = quality preserved, very large files, large storage; high-end cameras shoot raw lossless and normally require post-processing; lossy codecs use algorithms to remove still pixels)."},
    ('2021', 15): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (licensing fees and infringement, permission for photos and video, copyright licensing to prevent legal action, Australian classification so viewers can judge suitability, consumers following copyright law, protecting producers' intellectual property). The bank adds privacy/consent and fair use, both reasonable extensions of the same strand. NESA also lists WHS as an alternative; not covered, but the question asks for ethical issues and the bank gives four substantial ones."},
    ('2021', 16): {"verdict": 'ok', "fields": _ALL, "note": _SEC3 + "(a) Industrial Relations issues and (b) career and training opportunities; NESA's grid files both under 'Personnel issues'. (b) follows NESA's own two-branch structure (expansion vs downsizing) and links each strategy to its outcome, which is what the top band requires."},

    # ── 2022 ────────────────────────────────────────────────────────────────
    ('2022', 11): {"verdict": 'corrected', "fields": _ALL, "note": "The most consequential defect found in this review, and it cost marks. This 1-mark question asks the student to identify ONE advantage of PDF, but it carried SEVEN keywords with minKeywords 1, and the offline formula is proportional: a student who correctly identified one advantage matched about 3 of 7, and round(3/7 x 1) = 0, so a CORRECT answer scored 0/1. Measured across the subject, it was the only question that scored zero at its own stated threshold. Converted to acceptableAnswers ('formatting', 'platform', 'consistent', 'prevent', 'password', 'unauthorised'), which returns full marks on any one match -- the right semantics for 'identify ONE', and the mechanism the subject's other four 1-mark questions already use. Separately, 'platform' and 'cross-platform' appeared nowhere in the model answer; its first sentence now ends 'software platforms -- that is, they are cross-platform', taking 'platforms' from NESA's own sample ('formatting to be maintained across different software platforms'). Content was correct throughout and is unchanged."},
    ('2022', 12): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (a smaller copy of the original, used on a web page to reduce download time, and a preview so the full file need not be downloaded to be viewed). The bank adds bandwidth and gallery/playlist browsing, which its own model answer demonstrates."},
    ('2022', 13): {"verdict": 'ok', "fields": _ALL, "note": "NESA's sample here is readable prose rather than mangled table layout, and the bank follows it exactly: 550 MB x 8 = 4400 megabits, 4400 / 80 = 55 seconds. Marked ok rather than divergent-accepted for that reason -- unlike 2020/2021/2023 Q13. The single-character keyword '8' is loose in the same way noted on 2020 Q13."},
    ('2022', 14): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (dangerous activities completed safely in an immersive virtual environment, training for specialist fields such as the army and pilots, specialist hardware and software expensive to set up and maintain, motion sickness). The bank's surgeons/emergency responders and eye strain are extensions of NESA's own examples."},
    ('2022', 15): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (pre-made reference bank of assets, tweening and morphing when placing mouth shapes on the timeline, each shape matched to its corresponding audio sound, synchronising as the final step). The bank adds the phoneme and waveform terminology and the lip-sync name, all standard. NESA's 'saves the animator time' point is implicit in the bank rather than stated -- noted, not a defect at this mark value."},
    ('2022', 16): {"verdict": 'ok', "fields": _ALL, "note": _SEC3 + "(a) the role of WHS legislation and (b) strategies to improve safety; NESA's grid files both under 'Work, health and safety'. (b) is organised around the hierarchy of control, which NESA's own sample leads with, and explains how each strategy addresses a hazard rather than listing them, as the top band requires."},

    # ── 2023 ────────────────────────────────────────────────────────────────
    ('2023', 11): {"verdict": 'corrected', "fields": _ALL, "note": "acceptableAnswers already covered NESA's interactivity, sensory feedback and believability, plus immersion, presence and haptic. Corrected only in that it had NO bandDescriptors; added from NESA's single criteria row (degenerate N=1, partial/minimal authored non-attainment, as 2020 Q11)."},
    ('2023', 12): {"verdict": 'corrected', "fields": _ALL, "note": "Content matched NESA (high-resolution graphics significantly increase file size, leading to longer loading times and more storage, and requiring more processing power causing performance issues on lower-end devices). Corrected because the keyword 'bandwidth' appeared nowhere in the model answer and so could never be credited. The answer now reads 'require more storage space, consume more bandwidth and take longer to load'; NESA's own alternatives include 'Slower internet connection', which is the same idea. Nothing else changed."},
    ('2023', 13): {"verdict": 'divergent-accepted', "fields": _ALL, "note": "NESA's sample is a costing TABLE that extracts as run-together layout ('BUSINESS CARD COSTING Cost per unit Number of units required Total $0.85 800 $680 ...'), so the bank's worked prose necessarily reads unlike it. Compared numerically: 800 x $0.85 = $680, 800 x $0.10 gloss = $80, design $60 flat, total $820. Every figure agrees. NESA also prints an alternative costing at design $40 giving $800; the stem specifies $60, so $820 is the answer for this question. Numeric keywords are loose in the same way as 2020 Q13 ('80' and '60' are short)."},
    ('2023', 14): {"verdict": 'ok', "fields": _ALL, "note": "Follows NESA's process step for step (audio file added to the editing software library, selected and placed at the desired location on the timeline, fade in and fade out because abrupt cuts sound unnatural, volume adjusted, playback to test for accuracy and natural fit, repeat as necessary)."},
    ('2023', 15): {"verdict": 'ok', "fields": _ALL, "note": "Covers NESA's ethical strand (intellectual property, permissions and licences, copyright, fair use, reputational damage) and legal strand (liabilities, trademark law, privacy and consent, proper attribution). NESA also mentions defamation, which the bank does not name -- noted; the bank covers privacy and consent, and the question is answered comprehensively at 5 marks."},
    ('2023', 16): {"verdict": 'ok', "fields": _ALL, "note": _SEC3 + "The only year with a 3 + 12 split rather than 5 + 10. (a) is the degenerate N=3 criteria case, where the top/middle/bottom collapse maps one-to-one with no joining. (b) is the longest response in the subject at 12 marks and is written with advantages, disadvantages and an overall judgement, integrating industry examples (rendering farms, disc replication, template publishing, automated encoding) because NESA's top band requires them."},

    # ── 2024 ────────────────────────────────────────────────────────────────
    ('2024', 11): {"verdict": 'corrected', "fields": _ALL, "note": "acceptableAnswers covers NESA's MP3, MIDI, wav and wma, plus aac, flac and ogg. Corrected only in that it had NO bandDescriptors; added from NESA's single criteria row (degenerate N=1, partial/minimal authored non-attainment, as 2020 Q11)."},
    ('2024', 12): {"verdict": 'corrected', "fields": _ALL, "note": "Content matched NESA (serifs help distinguish letterforms and make text easier to read at small sizes, clearer in print, and easier for the eye to track and recognise words quickly). Corrected because the keyword 'recogni' appeared nowhere in the model answer. The answer now reads 'easier to track, distinguish and recognise individual words and characters quickly', taking 'recognise' from NESA's own sample. Nothing else changed."},
    ('2024', 13): {"verdict": 'corrected', "fields": _ALL, "note": "Content matched NESA (bitmaps are made of pixels, vectors of lines described by equations; zooming a bitmap makes it grainy while a vector stays smooth and sharp). Corrected because the keyword 'grainy' -- NESA's own word -- appeared nowhere in the model answer, which said only 'blurry or pixelated'. Now reads 'appear grainy, blurry or \"pixelated\"'. Nothing else changed."},
    ('2024', 14): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (close-up shots for intense emotion, wide shots to establish and set the scene, low angle for power or authority, tracking shots for cinematic impact) and adds medium and high-angle shots with examples, which the 'use examples' instruction invites."},
    ('2024', 15): {"verdict": 'ok', "fields": _ALL, "note": "Follows NESA closely (detailed storyboard identifying the effects scenes, assessment of software/hardware/skill-set requirements, green screens for chroma keying with actors, 3D models and textures and digital assets, lighting and coordination for seamless post-production integration, added effects layers, and the CGI-in-Marvel-films example NESA itself gives)."},
    ('2024', 16): {"verdict": 'ok', "fields": _ALL, "note": _SEC3 + "(a) compares marketing and advertising across the two firms and (b) analyses how their structures affect production and efficiency; NESA's grid files both under 'Structural considerations'. This is the only year whose stimulus NESA explicitly binds to both parts ('Use the following information to answer parts (a) and (b)'), so it is held in the shared stem and rendered once; the paper's italics on Organisation A and B are preserved."},

    # ── 2025 ────────────────────────────────────────────────────────────────
    ('2025', 11): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (PNG supports lossless compression so quality is not compromised, and supports transparent backgrounds, useful for web design and graphics requiring layering)."},
    ('2025', 12): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (adjust colours, saturation and overlays to match the brand aesthetic; suitable aspect ratio; contrast for text readability; optimise for fast loading; test responsiveness across devices)."},
    ('2025', 13): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (analogue uses continuous signals giving smooth natural transitions; digital uses discrete signals allowing better quality, easier editing and correction). The bank adds binary representation, generational loss and compression, all standard."},
    ('2025', 14): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA almost point for point (realistic fluid movement, reduced labour-intensive keyframing, improved efficiency, subtle emotion and expressiveness, reusable data with long-term value, and using MoCap selectively for complex scenes to balance cost and quality)."},
    ('2025', 15): {"verdict": 'ok', "fields": _ALL, "note": "Matches NESA (authenticity, misinformation and consumer deception; over-editing creating unrealistic beauty standards affecting mental health; altered images in journalism eroding trust; the positive example of pixelating a traumatic image to protect privacy; copyright and attribution; balancing creativity with honesty and transparency in advertising)."},
    ('2025', 16): {"verdict": 'ok', "fields": _ALL, "note": _SEC3 + "(a) the effects of legislative requirements on sustainable practices and (b) historical developments in manufacturing; NESA's grid files (a) under 'Environmental and sociological considerations - legislative requirements' and (b) under 'Historical developments'. (b) draws on NESA's own long alternatives list (mechanisation, digital technology, miniaturisation, CAD/CAM, robotics and CNC, cloud computing, circular economy) and closes with an overall judgement, as the top band requires."},
}
