#!/usr/bin/env node
/**
 * Check original HSC questions in subjects/*.json against the official answer
 * key in data/answer-key/*.json.
 *
 * WHY: an audit is a claim about one moment; a test is a standing guarantee.
 * Every previous attempt to verify these answers was a one-off reading exercise,
 * and each one reached a different conclusion. This check runs on every push, so
 * a wrong answer can never silently survive again.
 *
 * It reads no PDFs -- the NESA papers are not in the repo. Ground truth comes
 * only from the committed key, regenerated by scripts/build_answer_key.py.
 *
 * SCOPE: original HSC multiple-choice questions only. Questions marked
 * `variant: true` are AI-generated and have no official answer, so they are
 * skipped -- they need their own audit (see docs/HISTORY.md).
 *
 * A question is only checkable when it carries a `qNum` identifying which exam
 * question it is. Questions without one are reported as UNVERIFIABLE rather than
 * quietly passing: they are not known-good, they are unknown.
 *
 *   node scripts/check_answer_key.cjs
 *
 * Exits 1 if any answer contradicts the official key.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.join(__dirname, '..');
const KEY_DIR = path.join(REPO, 'data', 'answer-key');
const SUBJECT_DIR = path.join(REPO, 'subjects');
const LETTERS = ['A', 'B', 'C', 'D'];

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function plural(n, word) {
  return `${n} ${word}${n === 1 ? '' : 's'}`;
}

if (!fs.existsSync(KEY_DIR)) {
  console.log('No data/answer-key/ directory — nothing to check.');
  process.exit(0);
}

const keyFiles = fs.readdirSync(KEY_DIR).filter((f) => f.endsWith('.json'));
if (keyFiles.length === 0) {
  console.log('No answer-key files — nothing to check.');
  process.exit(0);
}

let wrongTotal = 0;
let checkedTotal = 0;
let unverifiableTotal = 0;

for (const keyFile of keyFiles.sort()) {
  const key = readJson(path.join(KEY_DIR, keyFile));
  const subjectPath = path.join(SUBJECT_DIR, `${key.subjectId}.json`);

  if (!fs.existsSync(subjectPath)) {
    console.error(`FAIL  ${key.subjectId}: answer key exists but subjects/${key.subjectId}.json does not`);
    wrongTotal += 1;
    continue;
  }

  const subject = readJson(subjectPath);
  const byYear = new Map();
  for (const q of subject.mcQuestions || []) {
    if (q.variant) continue; // AI-generated, no official answer
    if (!byYear.has(q.year)) byYear.set(q.year, []);
    byYear.get(q.year).push(q);
  }

  const wrong = [];
  const unverifiable = [];
  let checked = 0;

  for (const paper of key.papers) {
    const questions = byYear.get(paper.year) || [];
    const answers = paper.sectionI.answers;

    for (const q of questions) {
      if (q.qNum === undefined || q.qNum === null || q.qNum === '') {
        unverifiable.push({ year: paper.year, reason: 'no qNum', q });
        continue;
      }
      const official = answers[String(q.qNum)];
      if (!official) {
        unverifiable.push({ year: paper.year, reason: `Q${q.qNum} not in key`, q });
        continue;
      }
      if (!Number.isInteger(q.answer) || q.answer < 0 || q.answer > 3) {
        wrong.push({ year: paper.year, qNum: q.qNum, got: String(q.answer), official,
                     text: 'answer index is not 0-3' });
        continue;
      }
      checked += 1;
      const got = LETTERS[q.answer];
      if (got !== official) {
        wrong.push({
          year: paper.year,
          qNum: q.qNum,
          got,
          official,
          text: String(q.q).replace(/<[^>]+>/g, '').slice(0, 60),
          chose: String(q.options[q.answer]).replace(/<[^>]+>/g, '').slice(0, 34),
        });
      }
    }

    // every question in the key should exist in the bank
    const present = new Set(questions.filter((q) => q.qNum != null).map((q) => String(q.qNum)));
    const absent = Object.keys(answers).filter((n) => !present.has(n));
    if (questions.length && absent.length) {
      unverifiable.push({ year: paper.year, reason: `bank is missing Q${absent.join(', Q')}` });
    }
  }

  checkedTotal += checked;
  wrongTotal += wrong.length;
  unverifiableTotal += unverifiable.length;

  const status = wrong.length ? 'FAIL' : 'OK  ';
  console.log(`${status}  ${key.subjectId}: ${plural(checked, 'answer')} checked, ` +
              `${wrong.length} wrong, ${unverifiable.length} unverifiable`);

  for (const w of wrong.sort((a, b) => a.year - b.year || a.qNum - b.qNum)) {
    console.log(`        ${w.year} Q${w.qNum}: bank says ${w.got}, official is ${w.official}`);
    console.log(`            ${w.text}`);
    if (w.chose) console.log(`            bank's chosen option: ${w.chose}`);
  }
  for (const u of unverifiable.slice(0, 8)) {
    console.log(`        NOTE ${u.year}: ${u.reason}`);
  }
  if (unverifiable.length > 8) {
    console.log(`        NOTE ... and ${unverifiable.length - 8} more unverifiable`);
  }
}

console.log(`\n${plural(checkedTotal, 'answer')} checked against the official key, ` +
            `${wrongTotal} wrong, ${unverifiableTotal} unverifiable.`);

if (wrongTotal > 0) {
  console.error('\nAnswer-key check FAILED. These answers contradict the official ' +
                'NESA marking guidelines.');
  process.exit(1);
}
console.log('Answer-key check passed.');
