#!/usr/bin/env node
/**
 * Check written questions in subjects/*.json against the official mark
 * allocations in data/answer-key/written/*.json.
 *
 * WHY: the same reason as check_answer_key.cjs -- an audit is a claim about one
 * moment, a test is a standing guarantee. A written question's mark value drives
 * scoring and the AI marking prompt, so a wrong one is not cosmetic.
 *
 * It reads no PDFs -- the NESA papers are not in the repo. Ground truth comes only
 * from the committed key, regenerated by scripts/build_written_key.py.
 *
 * WHAT IS ENFORCED: the mark value only. The key also stores each part's official
 * sample answer, but prose cannot be compared for equality, so it is reference for
 * a human reviewer and is deliberately not asserted on here.
 *
 * THE JOIN. This is the part that needs care, and it is why the check aggregates
 * rather than matching part-for-part. The bank stores a question's parts three
 * different ways, sometimes within one subject:
 *
 *   "qNum": 16          one entry covering every part of Q16
 *   "qNum": "23(a)"     one entry per part
 *   "qNum": "19(b)(i)"  one entry per sub-part
 *
 * 2020 and 2021 Maths split some multi-part questions that 2022-2025 merge, so
 * `qNum` alone is not a sufficient key. Instead each bank entry's qNum is parsed
 * into a base number plus a part path, and its expected marks are the SUM of every
 * official leaf part whose path starts with that path. An entry for `16` therefore
 * sums all of Q16's parts; `19(b)` sums (b)(i) and (b)(ii); `19(b)(i)` matches that
 * leaf alone. Merged and split storage both reconcile under one rule.
 *
 * Parts the engine deliberately cannot present (e.g. graph-drawing) are declared on
 * the question as `omittedParts` and added back before comparing -- otherwise a
 * deliberate omission reads as a wrong mark value. See CLAUDE.md section 10, rule 5.
 *
 * A question with no `qNum`, or from a year the key does not cover, is reported
 * UNVERIFIABLE rather than quietly passing. Health and Movement Science has no past
 * papers at all (2026 is its first HSC year), so it has no key and is skipped.
 *
 *   node scripts/check_written_key.cjs
 *
 * Exits 1 if any mark value contradicts the official key.
 */

'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const REPO = path.join(__dirname, '..');
const KEY_DIR = path.join(REPO, 'data', 'answer-key', 'written');
const REVIEW_DIR = path.join(KEY_DIR, 'reviews');
const SUBJECT_DIR = path.join(REPO, 'subjects');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function plural(n, word) {
  return `${n} ${word}${n === 1 ? '' : 's'}`;
}

/**
 * "19(b)(i)" -> { base: 19, path: ['b', 'i'] };  16 -> { base: 16, path: [] }
 * Returns null when the qNum is missing or not in a recognised shape.
 */
function parseQNum(qNum) {
  if (qNum === undefined || qNum === null) return null;
  const raw = String(qNum).trim();
  const m = raw.match(/^(\d+)\s*((?:\([a-z]+\)\s*)*)$/i);
  if (!m) return null;
  const path = (m[2].match(/\(([a-z]+)\)/gi) || []).map((s) =>
    s.replace(/[()]/g, '').toLowerCase()
  );
  return { base: Number(m[1]), path };
}

function pathOf(part) {
  return part === null || part === undefined ? [] : String(part).split('.');
}

function startsWith(leafPath, prefix) {
  if (prefix.length > leafPath.length) return false;
  return prefix.every((seg, i) => seg === leafPath[i]);
}

/**
 * Fingerprint of NESA's sample answer, whitespace-normalised. Must stay identical to
 * scripts/build_review_ledger.py:fingerprint() -- an irrelevant re-wrap of the PDF text
 * layer must not void a review, but any change of WORDS must.
 */
function fingerprint(text) {
  const norm = String(text || '').replace(/\s+/g, ' ').trim();
  return 'sha256:' + crypto.createHash('sha256').update(norm, 'utf8').digest('hex');
}

/**
 * Fingerprint of the same text with word ORDER discarded. Must stay identical to
 * scripts/build_review_ledger.py:word_fingerprint().
 *
 * Separates the two ways a sample answer can stop matching its review:
 *   - the WORDS changed  -> NESA's official text moved. The review is void; re-read it.
 *   - only the ORDER changed -> our extractor re-laid the line out. NESA did not move,
 *     so the review still stands, and the entry is reported rather than failed.
 * The second case is real: fixing build_written_key.py's word-order bug on 2026-09-05
 * re-laid out 45 of VET's 76 sample answers with an IDENTICAL word multiset -- not one
 * word added, removed or altered anywhere.
 */
function wordFingerprint(text) {
  const words = (String(text || '').toLowerCase().match(/[^\W_]+/gu) || []).sort();
  return 'sha256:' + crypto.createHash('sha256').update(words.join(' '), 'utf8').digest('hex');
}

if (!fs.existsSync(KEY_DIR)) {
  console.log('No data/answer-key/written/ directory — nothing to check.');
  process.exit(0);
}

const keyFiles = fs.readdirSync(KEY_DIR).filter((f) => f.endsWith('.json'));
if (keyFiles.length === 0) {
  console.log('No written answer-key files — nothing to check.');
  process.exit(0);
}

let wrongTotal = 0;
let checkedTotal = 0;
let unverifiableTotal = 0;
let reviewFailures = 0;

for (const keyFile of keyFiles.sort()) {
  const subjectId = keyFile.replace(/\.json$/, '');
  const key = readJson(path.join(KEY_DIR, keyFile));

  const subjectFile = path.join(SUBJECT_DIR, `${subjectId}.json`);
  if (!fs.existsSync(subjectFile)) {
    console.log(`SKIP  ${subjectId}: no subjects/${subjectId}.json`);
    continue;
  }
  const subject = readJson(subjectFile);
  const written = subject.writtenQuestions || [];

  const wrong = [];
  const unverifiable = [];
  const officialSample = new Map(); // "year|qNum" -> NESA's sample text for that entry
  let checked = 0;

  for (const q of written) {
    const year = q.year === undefined || q.year === null ? null : String(q.year);
    const parts = year ? key.papers[year] : null;
    if (!parts) {
      unverifiable.push(`${year || 'no year'} q${q.qNum ?? '?'} (no key for that paper)`);
      continue;
    }

    const parsed = parseQNum(q.qNum);
    if (!parsed) {
      unverifiable.push(`${year} qNum=${JSON.stringify(q.qNum)} (unrecognised question number)`);
      continue;
    }

    const matches = parts.filter(
      (p) => p.question === parsed.base && startsWith(pathOf(p.part), parsed.path)
    );
    if (matches.length === 0) {
      unverifiable.push(
        `${year} Q${q.qNum} (no such question part in the official key)`
      );
      continue;
    }

    officialSample.set(`${year}|${q.qNum}`, matches.map((p) => p.sampleAnswer || '').join(' '));

    const official = matches.reduce((sum, p) => sum + p.marks, 0);
    const omitted = (q.omittedParts || []).reduce((sum, p) => sum + (p.marks || 0), 0);
    const stored = (q.marks || 0) + omitted;

    checked += 1;
    if (stored !== official) {
      const note = omitted ? ` [stored ${q.marks} + ${omitted} omitted]` : '';
      wrong.push(
        `${year} Q${q.qNum}: bank has ${stored} mark${stored === 1 ? '' : 's'}${note}, ` +
          `official is ${official} (${matches
            .map((p) => (p.part ? `(${p.part.split('.').join(')(')})=${p.marks}` : `=${p.marks}`))
            .join(' + ')})`
      );
    }
  }

  // Whole questions the engine cannot present at all (e.g. "draw a diagram") are
  // declared at subject level, so a coverage gap is visible in the data rather than
  // only in prose. Verify each declaration still names a real official question --
  // a stale one would quietly excuse nothing.
  const declaredOmissions = subject.omittedQuestions || [];
  for (const o of declaredOmissions) {
    const parts = key.papers[String(o.year)];
    const parsed = parseQNum(o.qNum);
    const matches =
      parts && parsed
        ? parts.filter(
            (p) => p.question === parsed.base && startsWith(pathOf(p.part), parsed.path)
          )
        : [];
    if (matches.length === 0) {
      wrong.push(
        `omittedQuestions declares ${o.year} Q${o.qNum}, which is not in the official key`
      );
      continue;
    }
    const official = matches.reduce((sum, p) => sum + p.marks, 0);
    if (o.marks !== official) {
      wrong.push(
        `omittedQuestions ${o.year} Q${o.qNum}: declared ${o.marks} marks, official is ${official}`
      );
    }
    if (written.some((q) => String(q.year) === String(o.year) && String(q.qNum) === String(o.qNum))) {
      wrong.push(
        `omittedQuestions ${o.year} Q${o.qNum} is declared omitted but is present in the bank`
      );
    }
  }

  // Reverse direction: every official leaf part should be claimed by exactly one
  // bank entry or omission. The forward check above cannot see a question that is
  // simply ABSENT, which is how 2020 Standard 2 sat at 84/85 for over a year.
  //
  // REPORTED, NOT ENFORCED. Two subjects have large, deliberate, documented gaps:
  // Multimedia has never ported Section III (Q16, 15 marks/paper) and VET's written
  // bank covers 23 of its 65 marks. Failing on those would turn CI red on decisions
  // already taken, so this prints a coverage line and leaves the exit code alone.
  const owners = [];
  for (const q of written) {
    const parsed = parseQNum(q.qNum);
    if (parsed) owners.push({ year: String(q.year), ...parsed });
  }
  for (const o of declaredOmissions) {
    const parsed = parseQNum(o.qNum);
    if (parsed) owners.push({ year: String(o.year), ...parsed });
  }
  let officialParts = 0;
  const unclaimed = [];
  for (const [year, parts] of Object.entries(key.papers)) {
    for (const p of parts) {
      officialParts += 1;
      const leaf = pathOf(p.part);
      const claimed = owners.some(
        (o) => o.year === year && o.base === p.question && startsWith(leaf, o.path)
      );
      if (!claimed) {
        unclaimed.push(
          `${year} Q${p.question}${leaf.length ? `(${leaf.join(')(')})` : ''} = ${p.marks}`
        );
      }
    }
  }

  checkedTotal += checked;
  wrongTotal += wrong.length;
  unverifiableTotal += unverifiable.length;

  const status = wrong.length ? 'WRONG' : 'OK   ';
  const omitNote = declaredOmissions.length
    ? `, ${plural(declaredOmissions.length, 'declared omission')}`
    : '';
  console.log(
    `${status} ${subjectId}: ${plural(checked, 'question')} checked, ` +
      `${wrong.length} wrong, ${unverifiable.length} unverifiable${omitNote}`
  );
  for (const line of wrong) console.log(`        ✗ ${line}`);
  for (const line of unverifiable) console.log(`        ? ${line}`);
  console.log(
    `        coverage: ${officialParts - unclaimed.length}/${officialParts} official ` +
      `parts claimed by a bank entry or a declared omission` +
      (unclaimed.length ? ` — ${unclaimed.length} not ported (reported, not enforced)` : '')
  );
  for (const line of unclaimed.slice(0, 6)) console.log(`        • ${line}`);
  if (unclaimed.length > 6) console.log(`        • ... and ${unclaimed.length - 6} more`);

  // ── Written-answer review coverage ──────────────────────────────────────────────
  //
  // The mark is the ONLY thing enforced above. Everything a written question teaches
  // or is marked on -- modelAnswer (shown straight to the student), keywords (AI
  // marking AND the offline grid) and bandDescriptors (the AI's band rubric) -- is
  // prose, and prose cannot be compared for equality. What CAN be checked is whether
  // a human compared it against NESA, and whether that comparison is still current.
  //
  // The ledger stores a fingerprint of NESA's sample answer AS AT REVIEW TIME, so
  // regenerating the key VOIDS any review whose official text moved rather than
  // letting it go quietly stale. See docs/porting-playbook.md section 6.
  //
  // REPORT-THEN-ENFORCE, opted in per subject by committing a ledger: a subject with
  // no ledger is reported at 0% and does not fail (four subjects carry historical
  // debt); a subject WITH one must stay fully reviewed, so an unreviewed or stale
  // question fails the build.
  const ledgerFile = path.join(REVIEW_DIR, `${subjectId}.json`);
  if (!fs.existsSync(ledgerFile)) {
    console.log(
      `        review:   0/${written.length} model answers reviewed against NESA ` +
        `— no ledger (reported, not enforced)`
    );
  } else {
    const ledger = readJson(ledgerFile);
    const unreviewed = [];
    const stale = [];
    const relaidOut = [];
    const verdicts = {};
    for (const q of written) {
      const entry = (ledger.reviews[String(q.year)] || {})[String(q.qNum)];
      if (!entry) {
        unreviewed.push(`${q.year} Q${q.qNum}`);
        continue;
      }
      verdicts[entry.verdict] = (verdicts[entry.verdict] || 0) + 1;
      const sample = officialSample.get(`${q.year}|${q.qNum}`);
      if (sample === undefined || fingerprint(sample) === entry.sampleAnswerFingerprint) continue;
      // The exact text moved. Only NESA's WORDS moving voids the review; a pure
      // re-layout by our own extractor does not. An older ledger with no word
      // fingerprint gets the strict answer, so this can never weaken an existing one.
      if (
        entry.sampleAnswerWordsFingerprint &&
        wordFingerprint(sample) === entry.sampleAnswerWordsFingerprint
      ) {
        relaidOut.push(`${q.year} Q${q.qNum}`);
      } else {
        stale.push(`${q.year} Q${q.qNum} (reviewed ${entry.reviewedAt})`);
      }
    }
    const reviewed = written.length - unreviewed.length;
    const summary = Object.keys(verdicts)
      .sort()
      .map((v) => `${verdicts[v]} ${v}`)
      .join(', ');
    console.log(
      `        review:   ${reviewed}/${written.length} reviewed against NESA` +
        (summary ? ` — ${summary}` : '') +
        (stale.length ? ` — ${stale.length} STALE` : '') +
        (relaidOut.length ? ` — ${relaidOut.length} re-laid out (wording unchanged)` : '')
    );
    for (const line of unreviewed) console.log(`        ✗ unreviewed: ${line}`);
    for (const line of stale) {
      console.log(`        ✗ stale review: ${line} — NESA's sample answer has changed`);
    }
    if (relaidOut.length) {
      console.log(
        `        · ${relaidOut.length} sample answer(s) re-laid out by the extractor since ` +
          'review — identical words, different order, so the reviews still stand: ' +
          relaidOut.slice(0, 6).join(', ') +
          (relaidOut.length > 6 ? `, +${relaidOut.length - 6} more` : '')
      );
    }
    reviewFailures += unreviewed.length + stale.length;
  }
}

console.log(
  `\n${plural(checkedTotal, 'written question')} checked against the official ` +
    `marks, ${wrongTotal} wrong, ${unverifiableTotal} unverifiable.`
);

if (wrongTotal > 0) {
  console.error(
    '\nWritten mark check FAILED. The official marks are ground truth — fix the ' +
      'question in subjects/, or declare a deliberately dropped part with ' +
      '`omittedParts` (CLAUDE.md section 10, rule 5). Never edit data/answer-key/ by hand.'
  );
  process.exit(1);
}
if (reviewFailures > 0) {
  console.error(
    `\nWritten-answer review check FAILED (${reviewFailures} question(s)). This subject ` +
      'has a committed review ledger, so every written question must stay reviewed. ' +
      'Read the question against NESA\'s sample answer and criteria in ' +
      'data/answer-key/written/, add or update its verdict in scripts/reviews/, then ' +
      'rebuild with scripts/build_review_ledger.py. A STALE entry means the official ' +
      'text itself moved — re-read that one, do not just re-fingerprint it.'
  );
  process.exit(1);
}
console.log('Written mark check passed.');
